analytics: {}
color:
  brandColors:
    - '#C0B8D8'
    - '#A87810'
    - '#A05880'
    - '#D8A018'
    - '#98A0D0'
  brandStrength: 0.97072
  lightness: 0.958936
  rhythmicContrast: 0.327702
  saturation: 0.319819
cta: {}
layout_spectrum: 0.898648
name: OurEoils
opengraph: {}
purpose: {}
typography_spectrum: 0.890765
